INSERT INTO stories (title, contents, status, created_on, author_id)
VALUES ('The Boy And The Filberts',' Once upon a time there was an old mother pig who had three little pigs and not enough food to feed them. So when they were old enough, she sent them out into the world to seek their fortunes.
The first little pig was very lazy. He did not want to work at all and he built his house out of straw. The second little pig worked a little bit harder but he was somewhat lazy too and he built his house out of sticks. Then, they sang and danced and played together the rest of the day.','In Progress',' 2020-10-24', 1),('The Three Little Pigs',' A Boy was given permission to put his hand into a pitcher to get some filberts. But he took such a great fistful that he could not draw his hand out again. There he stood, unwilling to give up a single filbert and yet unable to get them all out at once. Vexed and disappointed he began to cry.
""My boy,"" said his mother, ""be satisfied with half the nuts you have taken and you will easily get your hand out. Then perhaps you may have some more filberts some other time.""
Do not attempt too much at once.','Completed','2021-09-19', 2),
('A Cheeseburger',' Cheeseburgers make your knees weak and your soul tingle.
A great cheeseburger is a gastronomical event with so many varieties you couldn’t get tired of it if you tried.
There’s cheesy incarnation waiting for you no matter what your palate preferences are.
Unless you’re vegan, in which case we’re sorry for your loss.','In Progress','2021-08-29', 3),
('Give your project a caffeine kick!',' Black percolator, coffee beans robust frappuccino single origin. At dripper brewed, milk, dark fair trade foam and pumpkin spice cup extra. Americano mocha single origin, froth, coffee caffeine mug decaffeinated frappuccino blue mountain aftertaste aromatic. Grounds, roast rich kopi-luwak arabica aroma, qui, extraction foam bar  medium galão.
Cup beans variety, cappuccino white, organic foam aroma java caramelization redeye con panna. Saucer fair trade mug, shop, doppio caffeine at eu macchiato siphon robusta bar. Grounds qui mocha latte strong sugar to go bar  caramelization. Id, percolator cortado caramelization et coffee macchiato.','Completed','2021-03-30', 4),
('Far far away',' Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts','In Progress','2021-03-21', 5),
('Werther',' A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.
I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.
I am so happy, my dear friend, so absorbed in the exquisite sense of mere.','Completed','2021-01-16', 6),
('Kafka',' One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.
He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.
The bedding was hardly able to cover it and seemed ready.','In Progress','2021-02-06', 7),
('The European languages',' The European languages are members of the same family. Their separate existence is a myth.
For science, music, sport, etc, Europe uses the same vocabulary.
The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators.','Completed','2021-03-01', 8),
('Cicero',' I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.','In Progress','2021-07-19', 9),
('The Eyes Have It',' A poke at idioms, sci-fi style. If we read everything literally, we would go mad. You will be ""in stitches"" by the time you are done reading Dicks ""side-splitting"" story!','Completed','2021-04-16', 1),
('Wit Inspirations of the ""Two-Year-Olds""',' Samuel is a very excellent name. I saw that trouble was coming. Nothing could prevent it.','In Progress','2021-04-14', 2),
('Maine to the Rescue',' A late winter blizzard is just the occasion for Maine (the girl) to step out and save the day!','Completed',' 2020-12-24', 3),
('Give the People what they Think they want',' The Fable of the Preacher Who Flew His Kite, But Not Because He Wished to Do So. ""Give the People what they Think they want"" is the clear moral imperative in this story.','In Progress',' 2020-12-18', 4),
('A Strange Story',' As the title implies, O. Henry delivers an unexpected story about a delayed errand in search of cough medicine that requires patients-- two, in fact.','Completed','2021-01-23', 5),
('Lord Oakhurst Curse',' This story would make a steam piano go out behind a barn and kick itself in despair.','In Progress','2021-10-12', 6),
('A Telephonic Conversation',' Twain  humorous rant contrasting how women talk on the telephone compared to men.','Completed',' 2020-11-30', 7),
('The dog',' A dog always looks as if he ought to have a pipe in his mouth and a black bag for his lunch, and then he would go quite happily to office every day.','In Progress','2021-05-01', 8),
('The Patient Cat',' Well, of all the horrid, mean, ungrateful creatures I ever saw, those birds are the horridest, and the meanest, and the most ungrateful!','Completed',' 2020-11-10', 9),
('A Monument to Adam',' We had monkeys, and missing links, and plenty of other kinds of ancestors, but no Adam.','In Progress','2021-06-03', 10),
('The Whistle',' When I see a beautiful sweet-tempered girl married to an ill-natured brute of a husband, What a pity, say I, that she should pay so much for a whistle!.','Completed',' 2020-12-20', 11);
INSERT INTO stories (title, contents, status, created_on, author_id)
VALUES ('THE THREE LITTLE PIGS','Once upon a time there were three little pigs and the time came for them to leave home and seek their fortunes. Before they left, their mother told them " Whatever you do , do it the best that you can because that is the way to get along in the world.
The first little pig built his house out of straw because it was the easiest thing to do. The second little pig built his house out of sticks. This was a little bit stronger than a straw house. The third little pig built his house out of bricks.
One night the big bad wolf, who dearly loved to eat fat little piggies, came along and saw the first little pig in his house of straw. He said "Let me in, Let me in, little pig or I shall huff and I shall puff and I shall blow your house in!" "Not by the hair of my chinny chin chin", said the little pig. But of course the wolf did blow the house in and ate the first little pig.
The wolf then came to the house of sticks. "Let me in ,Let me in little pig or I shall huff and I shall puff and I shall blow your house in" "Not by the hair of my chinny chin chin", said the little pig. But the wolf blew that house in too, and ate the second little pig.
The wolf then came to the house of bricks. " Let me in , let me in" cried the wolf "Or I shall huff and I shall puff till I blow your house in" "Not by the hair of my chinny chin chin" said the pigs. Well, the wolf huffed and puffed but he could not blow down that brick house.
But the wolf was a sly old wolf and he climbed up on the roof to look for a way into the brick house.
The little pig saw the wolf climb up on the roof and lit a roaring fire in the fireplace and placed on it a large kettle of water.
When the wolf finally found the hole in the chimney he crawled down and KERSPLASH right into that kettle of water and that was the end of his troubles with the big bad wolf.
The next day the little pig invited his mother over . She said "You see it is just as I told you. The way to get along in the world is to do things as well as you can." Fortunately for that little pig, he learned that lesson. And he just lived happily ever after!','In Progress','2021-01-27','12'),
('The Velveteen Rabbit','There was once a velveteen rabbit, and in the beginning he was really splendid. He was fat and bunchy, as a rabbit should be; his coat was spotted brown and white, he had real thread whiskers, and his ears were lined with pink sateen. On Christmas morning, when he sat wedged in the top of the Boy stocking, with a sprig of holly between his paws, the effect was charming.
There were other things in the stocking, nuts and oranges and a toy engine, and chocolate almonds and a clockwork mouse, but the Rabbit was quite the best of all. For at least two hours the Boy loved him, and then Aunts and Uncles came to dinner, and there was a great rustling of tissue paper and unwrapping of parcels, and in the excitement of looking at all the new presents the Velveteen Rabbit was forgotten.
For a long time he lived in the toy cupboard or on the nursery floor, and no one thought very much about him. He was naturally shy, and being only made of velveteen, some of the more expensive toys quite snubbed him. The mechanical toys were very superior, and looked down upon every one else; they were full of modern ideas, and pretended they were real. The model boat, who had lived through two seasons and lost most of his paint, caught the tone from them and never missed an opportunity of referring to his rigging in technical terms. The Rabbit could not claim to be a model of anything, for he did not know that real rabbits existed; he thought they were all stuffed with sawdust like himself, and he understood that sawdust was quite out-of-date and should never be mentioned in modern circles. Even Timothy, the jointed wooden lion, who was made by the disabled soldiers, and should have had broader views, put on airs and pretended he was connected with Government. Between them all the poor little Rabbit was made to feel himself very insignificant and commonplace, and the only person who was kind to him at all was the Skin Horse.
The Velveteen Rabbit and other Christmas toysThe Skin Horse had lived longer in the nursery than any of the others. He was so old that his brown coat was bald in patches and showed the seams underneath, and most of the hairs in his tail had been pulled out to string bead necklaces. He was wise, for he had seen a long succession of mechanical toys arrive to boast and swagger, and by-and-by break their mainsprings and pass away, and he knew that they were only toys, and would never turn into anything else. For nursery magic is very strange and wonderful, and only those playthings that are old and wise and experienced like the Skin Horse understand all about it.
"What is REAL?" asked the Rabbit one day, when they were lying side by side near the nursery fender, before Nana came to tidy the room. "Does it mean having things that buzz inside you and a stick-out handle?"
"Real is not how you are made," said the Skin Horse. "It is a thing that happens to you. When a child loves you for a long, long time, not just to play with, but REALLY loves you, then you become Real."
"Does it hurt?" asked the Rabbit.
"Sometimes," said the Skin Horse, for he was always truthful. "When you are Real you do not mind being hurt."
"Does it happen all at once, like being wound up," he asked, "or bit by bit?"
"It does not happen all at once," said the Skin Horse. "You become. It takes a long time. That is why it does not often happen to people who break easily, or have sharp edges, or who have to be carefully kept. Generally, by the time you are Real, most of your hair has been loved off and your eyes drop out and you get loose in the joints and very shabby. But these things do not matter at all, because once you are Real you ca not be ugly, except to people who do not understand."
"I suppose you are Real?" said the Rabbit. And then he wished he had not said it, for he thought the Skin Horse might be sensitive. But the Skin Horse only smiled.
"The Boy is Uncle made me Real," he said. "That was a great many years ago; but once you are Real you ca not become unreal again. It lasts for always."
The Rabbit sighed. He thought it would be a long time before this magic called Real happened to him. He longed to become Real, to know what it felt like; and yet the idea of growing shabby and losing his eyes and whiskers was rather sad. He wished that he could become it without these uncomfortable things happening to him.
There was a person called Nana who ruled the nursery. Sometimes she took no notice of the playthings lying about, and sometimes, for no reason whatever, she went swooping about like a great wind and hustled them away in cupboards. She called this "tidying up," and the playthings all hated it, especially the tin ones. The Rabbit did not mind it so much, for wherever he was thrown he came down soft.
One evening, when the Boy was going to bed, he could not find the china dog that always slept with him. Nana was in a hurry, and it was too much trouble to hunt for china dogs at bedtime, so she simply looked about her, and seeing that the toy cupboard door stood open, she made a swoop.
"Here," she said, "take your old Bunny! He will do to sleep with you!" And she dragged the Rabbit out by one ear, and put him into the Boy is arms.
That night, and for many nights after, the Velveteen Rabbit slept in the Boy is bed. At first he found it rather uncomfortable, for the Boy hugged him very tight, and sometimes he rolled over on him, and sometimes he pushed him so far under the pillow that the Rabbit could scarcely breathe. And he missed, too, those long moonlight hours in the nursery, when all the house was silent, and his talks with the Skin Horse. But very soon he grew to like it, for the Boy used to talk to him, and made nice tunnels for him under the bedclothes that he said were like the burrows the real rabbits lived in. And they had splendid games together, in whispers, when Nana had gone away to her supper and left the nightlight burning on the mantelpiece. And when the Boy dropped off to sleep, the Rabbit would snuggle down close under his little warm chin and dream, with the Boy is hands clasped close round him all night long.
And so time went on, and the little Rabbit was very happy—so happy that he never noticed how his beautiful velveteen fur was getting shabbier and shabbier, and his tail coming unsewn, and all the pink rubbed off his nose where the Boy had kissed him.
Spring came, and they had long days in the The Velveteen Rabbit is happy and lovedgarden, for wherever the Boy went the Rabbit went too. He had rides in the wheelbarrow, and picnics on the grass, and lovely fairy huts built for him under the raspberry canes behind the flower border. And once, when the Boy was called away suddenly to go out to tea, the Rabbit was left out on the lawn until long after dusk, and Nana had to come and look for him with the candle because the Boy could not go to sleep unless he was there. He was wet through with the dew and quite earthy from diving into the burrows the Boy had made for him in the flower bed, and Nana grumbled as she rubbed him off with a corner of her apron.
"You must have your old Bunny!" she said. "Fancy all that fuss for a toy!"
The Boy sat up in bed and stretched out his hands.
"Give me my Bunny!" he said. "You must not say that. He is not a toy. He is REAL!"
When the little Rabbit heard that he was happy, for he knew that what the Skin Horse had said was true at last. The nursery magic had happened to him, and he was a toy no longer. He was Real. The Boy himself had said it.
That night he was almost too happy to sleep, and so much love stirred in his little sawdust heart that it almost burst. And into his boot-button eyes, that had long ago lost their polish, there came a look of wisdom and beauty, so that even Nana noticed it next morning when she picked him up, and said, "I declare if that old Bunny has not got quite a knowing expression!"
That was a wonderful Summer!
Near the house where they lived there was a wood, and in the long June evenings the Boy liked to go there after tea to play. He took the Velveteen Rabbit with him, and before he wandered off to pick flowers, or play at brigands among the trees, he always made the Rabbit a little nest somewhere among the bracken, where he would be quite cosy, for he was a kind-hearted little boy and he liked Bunny to be comfortable. One evening, while the Rabbit was lying there alone, watching the ants that ran to and fro between his velvet paws in the grass, he saw two strange beings creep out of the tall bracken near him.
They were rabbits like himself, but quite furry and brand-new. They must have been very well The Velveteen Rabbit plays outsidemade, for their seams did not show at all, and they changed shape in a queer way when they moved; one minute they were long and thin and the next minute fat and bunchy, instead of always staying the same like he did. Their feet padded softly on the ground, and they crept quite close to him, twitching their noses, while the Rabbit stared hard to see which side the clockwork stuck out, for he knew that people who jump generally have something to wind them up. But he could not see it. They were evidently a new kind of rabbit altogether.
They stared at him, and the little Rabbit stared back. And all the time their noses twitched.
"Why do not you get up and play with us?" one of them asked.
"I do not feel like it," said the Rabbit, for he did not want to explain that he had no clockwork.
"Ho!" said the furry rabbit. "It is as easy as anything." And he gave a big hop sideways and stood on his hind legs.
"I do not believe you can!" he said.
"I can!" said the little Rabbit. "I can jump higher than anything!" He meant when the Boy threw him, but of course he did not want to say so.
"Can you hop on your hind legs?" asked the furry rabbit.
That was a dreadful question, for the Velveteen Rabbit had no hind legs at all! The back of him was made all in one piece, like a pincushion. He sat still in the bracken, and hoped that the other rabbits would not notice.
"I do not want to!" he said again.
But the wild rabbits have very sharp eyes. And this one stretched out his neck and looked.
"He has not got any hind legs!" he called out. "Fancy a rabbit without any hind legs!" And he began to laugh.
"I have!" cried the little Rabbit. "I have got hind legs! I am sitting on them!"
"Then stretch them out and show me, like this!" said the wild rabbit. And he began to whirl round and dance, till the little Rabbit got quite dizzy.
"I do not like dancing," he said. "Iwould rather sit still!"
But all the while he was longing to dance, for a funny new tickly feeling ran through him, and he felt he would give anything in the world to be able to jump about like these rabbits did.
The strange rabbit stopped dancing, and came quite close. He came so close this time that his long whiskers brushed the Velveteen Rabbit is ear, and then he wrinkled his nose suddenly and flattened his ears and jumped backwards.
"He does not smell right!" he exclaimed. "He is not a rabbit at all! He is not real!"
"I am Real!" said the little Rabbit, "I am Real! The Boy said so!" And he nearly began to cry.
Just then there was a sound of footsteps, and the Boy ran past near them, and with a stamp of feet and a flash of white tails the two strange rabbits disappeared.
"Come back and play with me!" called the little Rabbit. "Oh, do came back! I know I am Real!"
But there was no answer, only the little ants ran to and fro, and the bracken swayed gently where the two strangers had passed. The Velveteen Rabbit was all alone.
"Oh, dear!" he thought. "Why did they run away like that? Why could not they stop and talk to me?" For a long time he lay very still, watching the bracken, and hoping that they would come back. But they never returned, and presently the sun sank lower and the little white moths fluttered out, and the Boy came and carried him home.
Weeks passed, and the little Rabbit grew very old and shabby, but the Boy loved him just as much. He loved him so hard that he loved all his whiskers off, and the pink lining to his ears turned grey, and his brown spots faded. He even began to lose his shape, and he scarcely looked like a rabbit any more, except to the Boy. To him he was always beautiful, and that was all that the little Rabbit cared about. He did not mind how he looked to other people, because the nursery magic had made him Real, and when you are Real shabbiness does not matter.
And then, one day, the Boy was ill.
His face grew very flushed, and he talked in his sleep, and his little body was so hot that it burned the Rabbit when he held him close. Strange people came and went in the nursery, and a light burned all night, and through it all the little Velveteen Rabbit lay there, hidden from sight under the bedclothes, and he never stirred, for he The Velveteen Rabbit loves the boy and waits patiently for himwas afraid that if they found him some one might take him away, and he knew that the Boy needed him.
It was a long weary time, for the Boy was too ill to play, and the little Rabbit found it rather dull with nothing to do all day long. But he snuggled down patiently, and looked forward to the time when the Boy should be well again, and they would go out in the garden amongst the flowers and the butterflies and play splendid games in the raspberry thicket like they used to. All sorts of delightful things he planned, and while the Boy lay half asleep he crept up close to the pillow and whispered them in his ear. And presently the fever turned, and the Boy got better. He was able to sit up in bed and look at picture books, while the little Rabbit cuddled close at his side. And one day, they let him get up and dress.
It was a bright, sunny morning, and the windows stood wide open. They had carried the Boy out on to the balcony, wrapped in a shawl, and the little Rabbit lay tangled up among the bedclothes, thinking.
The Boy was going to the seaside to-morrow. Everything was arranged, and now it only remained to carry out the doctor is orders. They talked about it all, while the little Rabbit lay under the bedclothes, with just his head peeping out, and listened. The room was to be disinfected, and all the books and toys that the Boy had played with in bed must be burnt.
"Hurrah!" thought the little Rabbit. "To-morrow we shall go to the seaside!" For the Boy had often talked of the seaside, and he wanted very much to see the big waves coming in, and the tiny crabs, and the sand castles.
Just then Nana caught sight of him.
"How about his old Bunny?" she asked.
"That?" said the doctor. "Why, it is a mass of scarlet fever germs!—Burn it at once. What? Nonsense! Get him a new one. He must not have that any more!"
And so the little Rabbit was put into a sack with the old picture-books and a lot of rubbish, and carried out to the end of the garden behind the fowl-house. That was a fine place to make a bonfire, only the gardener was too busy just then to attend to it. He had the potatoes to dig and the green peas to gather, but next morning he promised to come quite early and burn the whole lot.
That night the Boy slept in a different bedroom, and he had a new bunny to sleep with him. It was a splendid bunny, all white plush with real glass eyes, but the Boy was too excited to care very much about it. For to-morrow he was going to the seaside, and that in itself was such a wonderful thing that he could think of nothing else.
And while the Boy was asleep, dreaming of the seaside, the little Rabbit lay among the old picture-books in the corner behind the fowlhouse, and he felt very lonely. The sack had been left untied, and so by wriggling a bit he was able to get his head through the opening and look out. He was shivering a little, for he had always been used to sleeping in a proper bed, and by this time his coat had worn so thin and threadbare from hugging that it was no longer any protection to him. Near by he could see the thicket of raspberry canes, growing tall and close like a tropical jungle, in whose shadow he had played with the Boy on bygone mornings. He thought of those long sunlit hours in the garden—how happy they were—and a great sadness came over him. He seemed to see them all pass before him, each more beautiful than the other, the fairy huts in the flower-bed, the quiet evenings in the wood when he lay in the bracken and the little ants ran over his paws; the wonderful day when he first knew that he was Real. He thought of the Skin Horse, so wise and gentle, and all that he had told him. Of what use was it to be loved and lose one is beauty and become Real if it all ended like this? And a tear, a real tear, trickled down his little shabby velvet nose and fell to the ground.
And then a strange thing happened. For where the tear had fallen a flower grew out of the ground, a mysterious flower, not at all like any that grew in the garden. It had slender green leaves the colour of emeralds, and in the centre of the leaves a blossom like a golden cup. It was so beautiful that the little Rabbit forgot to cry, and just lay there watching it. And presently the blossom opened, and out of it there stepped a fairy.
She was quite the loveliest fairy in the whole world. Her dress was of pearl and dewdrops, and there were flowers round her neck and in her hair, and her face was like the most perfect flower of all. And she came close to the little Rabbit and gathered him up in her arms and kissed him The lovely fairy brings magic to the story.on his velveteen nose that was all damp from crying.
"Little Rabbit," she said, "do not you know who I am?"
The Rabbit looked up at her, and it seemed to him that he had seen her face before, but he could not think where.
"I am the nursery magic Fairy," she said. "I take care of all the playthings that the children have loved. When they are old and worn out and the children do not need them any more, then I come and take them away with me and turn them into Real."
"Was not I Real before?" asked the little Rabbit.
"You were Real to the Boy," the Fairy said, "because he loved you. Now you shall be real to every one."
And she held the little Rabbit close in her arms and flew with him into the wood.

It was light now, for the moon had risen. All the forest was beautiful, and the fronds of the bracken shone like frosted silver. In the open glade between the tree-trunks the wild rabbits danced with their shadows on the velvet grass, but when they saw the Fairy they all stopped dancing and stood round in a ring to stare at her.
"I’ve brought you a new playfellow," the Fairy said. "You must be very kind to him and teach him all he needs to know in Rabbitland, for he is going to live with you for ever and ever!"

And she kissed the little Rabbit again and put him down on the grass.
"Run and play, little Rabbit!" she said.
But the little Rabbit sat quite still for a moment and never moved. For when he saw all the wild rabbits dancing around him he suddenly remembered about his hind legs, and he did not want them to see that he was made all in one piece. He did not know that when the Fairy kissed him that last time she had changed him altogether. And he might have sat there a long time, too shy to move, if just then something had not tickled his nose, and before he thought what he was doing he lifted his hind toe to scratch it.

And he found that he actually had hind legs! Instead of dingy velveteen he had brown fur, soft and shiny, his ears twitched by themselves, and his whiskers were so long that they brushed the grass. He gave one leap and the joy of using those hind legs was so great that he went springing about the turf on them, jumping sideways and whirling round as the others did, and he grew so excited that when at last he did stop to look for the Fairy she had gone.
He was a Real Rabbit at last, at home with the other rabbits.
Autumn passed and Winter, and in the Spring, when the days grew warm and sunny, the Boy went out to play in the wood behind the house. And while he was playing, two rabbits crept out from the bracken and peeped at him. One of them was brown all over, but the other had strange markings under his fur, as though long ago he had been spotted, and the spots still showed through. And about his little soft nose and his round black eyes there was something familiar, so that the Boy thought to himself:

"Why, he looks just like my old Bunny that was lost when I had scarlet fever!"

But he never knew that it really was his own Bunny, come back to look at the child who had first helped him to be Real.','Completed','2021-02-26','12'),
('Jack and the Beanstalk','Once upon a time there lived a poor widow and her son Jack. One day, Jack is mother told him to sell their only cow. Jack went to the market and on the way he met a man who wanted to buy his cow. Jack asked, “What will you give me in return for my cow?” The man answered, “I will give you five magic beans!” Jack took the magic beans and gave the man the cow. But when he reached home, Jack is mother was very angry. She said, “You fool! He took away your cow and gave you some beans!” She threw the beans out of the window. Jack was very sad and went to sleep without dinner.

The next day, when Jack woke up in the morning and looked out of the window, he saw that a huge beanstalk had grown from his magic beans! He climbed up the beanstalk and reached a kingdom in the sky. There lived a giant and his wife. Jack went inside the house and found the giant is wife in the kitchen. Jack said, “Could you please give me something to eat? I am so hungry!” The kind wife gave him bread and some milk.

While he was eating, the giant came home. The giant was very big and looked very fearsome. Jack was terrified and went and hid inside. The giant cried, “Fee-fi-fo-fum, I smell the blood of an Englishman. Be he alive, or be he dead, I shall grind his bones to make my bread!” The wife said, “There is no boy in here!” So, the giant ate his food and then went to his room. He took out his sacks of gold coins, counted them and kept them aside. Then he went to sleep. In the night, Jack crept out of his hiding place, took one sack of gold coins and climbed down the beanstalk. At home, he gave the coins to his mother. His mother was very happy and they lived well for sometime.

Jack and the Beanstalk Fee Fi Fo Fum!Climbed the beanstalk and went to the giant is house again. Once again, Jack asked the giant is wife for food, but while he was eating the giant returned. Jack leapt up in fright and went and hid under the bed. The giant cried, “Fee-fifo-fum, I smell the blood of an Englishman. Be he alive, or be he dead, I shall grind his bones to make my bread!” The wife said, “There is no boy in here!” The giant ate his food and went to his room. There, he took out a hen. He shouted, “Lay!” and the hen laid a golden egg. When the giant fell asleep, Jack took the hen and climbed down the beanstalk. Jack is mother was very happy with him.

After some days, Jack once again climbed the beanstalk and went to the giant is castle. For the third time, Jack met the giant is wife and asked for some food. Once again, the giant is wife gave him bread and milk. But while Jack was eating, the giant came home. “Fee-fi-fo-fum, I smell the blood of an Englishman. Be he alive, or be he dead, I shall grind his bones to make my bread!” cried the giant. “Do not be silly! There is no boy in here!” said his wife.

The giant had a magical harp that could play beautiful songs. While the giant slept, Jack took the harp and was about to leave. Suddenly, the magic harp cried, “Help master! A boy is stealing me!” The giant woke up and saw Jack with the harp. Furious, he ran after Jack. But Jack was too fast for him. He ran down the beanstalk and reached home. The giant followed him down. Jack quickly ran inside his house and fetched an axe. He began to chop the beanstalk. The giant fell and died.

Jack and his mother were now very rich and they lived happily ever after.','In Progress','2021-01-27','12'),
('The Tale of Peter Rabbit','ONCE upon a time there were four little Rabbits, and their names were— Flopsy, Mopsy, Cotton-tail, and Peter.
They lived with their Mother in a sand-bank, underneath the root of a very big fir tree.
"NOW, my dears," said old Mrs. Rabbit one morning, "you may go into the fields or down the lane, but do not go into Mr. McGregor is garden: your Father had an accident there; he was put in a pie by Mrs. McGregor."
"NOW run along, and do not get into mischief. I am going out."
THEN old Mrs. Rabbit took a basket and her umbrella, to the baker is. She bought a loaf of brown bread and five currant buns.
FLOPSY, Mopsy, and Cottontail, who were good little bunnies, went down the lane to gather blackberries;
Peter Rabbit gateBUT Peter, who was very naughty, ran straight away to Mr. McGregor is garden and squeezed under the gate!
FIRST he ate some lettuces and some French beans; and then he ate some radishes;
AND then, feeling rather sick, he went to look for some parsley.
BUT round the end of a cucumber frame, whom should he meet but Mr. McGregor!
MR. McGREGOR was on his hands and knees planting out young cabbages, but he jumped up and ran after Peter, waving a rake and calling out, "Stop thief!"
PETER was most dreadfully frightened; he rushed all over the garden, for he had forgotten the way back to the gate.
He lost one of his shoes among the cabbages, and the other shoe amongst the potatoes.
AFTER losing them, he ran on four legs and went faster, so that I think he might have got away altogether if he had not unfortunately run into a gooseberry net, and got caught by the large buttons on his jacket. It was a blue jacket with brass buttons, quite new.
Peter Rabbit gooseberry nextPETER gave himself up for lost, and shed big tears; but his sobs were overheard by some friendly sparrows, who flew to him in great excitement, and implored him to exert himself.
MR. McGREGOR came up with a sieve, which he intended to pop upon the top of Peter; but Peter wriggled out just in time, leaving his jacket behind him.
AND rushed into the toolshed, and jumped into a can. It would have been a beautiful thing to hide in, if it had not had so much water in it.
MR. McGREGOR was quite sure that Peter was somewhere in the toolshed, perhaps hidden underneath a flower-pot. He began to turn them over carefully, looking under each.
Presently Peter sneezed— "Kertyschoo!" Mr. McGregor was after him in no time,
AND tried to put his foot upon Peter, who jumped out of a window, upsetting three plants. The window was too small for Mr. McGregor, and he was tired of running after Peter. He went back to his work.
PETER sat down to rest; he was out of breath and trembling with fright, and he had not the least idea which way to go. Also he was very damp with sitting in that can.
After a time he began to wander about, going lippity— lippity—not very fast, and looking all around.
HE found a door in a wall; but it was locked, and there was no room for a fat little rabbit to squeeze underneath.
An old mouse was running in and out over the stone doorstep, carrying peas and beans to her family in the wood. Peter asked her the way to the gate, but she had such a large pea in her mouth that she could not answer. She only shook her head at him. Peter began to cry.
Peter Rabbit in wheelbarrowTHEN he tried to find his way straight across the garden, but he became more and more puzzled. Presently, he came to a pond where Mr. McGregor filled his water-cans. A white cat was staring at some gold-fish; she sat very, very still, but now and then the tip of her tail twitched as if it were alive. Peter thought it best to go away without speaking to her; he had heard about cats from his cousin, little Benjamin Bunny.
HE went back towards the tool-shed, but suddenly, quite close to him, he heard the noise of a hoe—scr-r-ritch, scratch, scratch, scritch. Peter scuttered underneath the bushes. But presently, as nothing happened, he came out, and climbed upon a wheelbarrow, and peeped over. The first thing he saw was Mr. McGregor hoeing onions. His back was turned towards Peter, and beyond him was the gate!
PETER got down very quietly off the wheelbarrow, and started running as fast as he could go, along a straight walk behind some black-currant bushes.
Mr. McGregor caught sight of him at the corner, but Peter did not care. He slipped underneath the gate, and was safe at last in the wood outside the garden.
Peter Rabbit hung coat shoesMR. McGREGOR hung up the little jacket and the shoes for a scare-crow to frighten the blackbirds.
PETER never stopped running or looked behind him till he got home to the big fir-tree.
He was so tired that he flopped down upon the nice soft sand on the floor of the rabbit-hole, and shut his eyes. His mother was busy cooking; she wondered what he had done with his clothes. It was the second little jacket and pair of shoes that Peter had lost in a fortnight!
I AM sorry to say that Peter was not very well during the evening.
His mother put him to bed, and made some camomile tea; and she gave a dose of it to Peter!
"One table-spoonful to be taken at bed-time."
BUT Flopsy, Mopsy, and Cotton-tail had bread and milk and blackberries, for supper.','Completed','2021-03-28','12'),
('The Elves and The Shoemaker','A shoemaker, by no fault of his own, had become so poor that at last he had nothing left but leather for one pair of shoes. So in the evening, he cut out the shoes which he wished to begin to make the next morning, and as he had a good conscience, he lay down quietly in his bed, commended himself to God, and fell asleep. In the morning, after he had said his prayers, and was just going to sit down to work, the two shoes stood quite finished on his table. He was astounded, and knew not what to say to it. He took the shoes in his hands to observe them closer, and they were so neatly made that there was not one bad stitch in them, just as if they were intended as a masterpiece. Soon after, a buyer came in, and as the shoes pleased him so well, he paid more for them than was customary, and, with the money, the shoemaker was able to purchase leather for two pairs of shoes. He cut them out at night, and next morning was about to set to work with fresh courage; but he had no need to do so, for, when he got up, they were already made, and buyers also were not wanting, who gave him money enough to buy leather for four pairs of shoes. The following morning, too, he found the four pairs made; and so it went on constantly, what he cut out in the evening was finished by the…','In Progress','2021-02-28','12');
